# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: story.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'story.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstory.proto\x12\x05story\"S\n\x17\x43reateCollectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x1a\n\x12mint_fee_recipient\x18\x03 \x01(\t\"[\n\x12\x43ollectionResponse\x12\x1a\n\x12\x63ollection_address\x18\x01 \x01(\t\x12\x18\n\x10transaction_hash\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"~\n\x14RegisterAssetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x14\n\x0ctext_content\x18\x04 \x01(\t\x12\x1a\n\x12\x63ollection_address\x18\x05 \x01(\t\"L\n\rAssetResponse\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x18\n\x10transaction_hash\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xa1\x01\n\x0cStoryService\x12M\n\x10\x43reateCollection\x12\x1e.story.CreateCollectionRequest\x1a\x19.story.CollectionResponse\x12\x42\n\rRegisterAsset\x12\x1b.story.RegisterAssetRequest\x1a\x14.story.AssetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'story_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOLLECTIONREQUEST']._serialized_start=22
  _globals['_CREATECOLLECTIONREQUEST']._serialized_end=105
  _globals['_COLLECTIONRESPONSE']._serialized_start=107
  _globals['_COLLECTIONRESPONSE']._serialized_end=198
  _globals['_REGISTERASSETREQUEST']._serialized_start=200
  _globals['_REGISTERASSETREQUEST']._serialized_end=326
  _globals['_ASSETRESPONSE']._serialized_start=328
  _globals['_ASSETRESPONSE']._serialized_end=404
  _globals['_STORYSERVICE']._serialized_start=407
  _globals['_STORYSERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
