packages:
  - "packages/*"
  - "packages/devhub/*"
  - "packages/app/*"
  - "packages/authoring/*"
  - "packages/story-generator/*"
  - "packages/infrastructure/*"
  - "packages/shared/*"
  - "packages/application/*"
  - "packages/admin-api/*"
