packages:
  - "packages/*"
  - "packages/app/*"
  - "packages/chain"
  - "packages/publisher"
  - "infra"
  - "tools/*"
  # Exclude admin-ui as it's a submodule with its own lockfile
  - "!packages/admin-ui"

