packages:
  - "packages/*"
  - "packages/infrastructure/*"
  - "packages/shared/*"
  - "packages/application/*"
  - "packages/authoring/*"
  - "apps/admin/api/*"
  - "apps/admin/ui/*"
  - "apps/app/*"
  - "apps/devhub/*"
  - "apps/identity/*"
  - "apps/publisher/*"
  - "apps/story-generator/*"
