packages:
  - "packages/*"
  - "packages/infrastructure/*"
  - "packages/shared/*"
  - "packages/application/*"
  - "packages/authoring/*"
  - "apps/admin/ui"
  - "apps/devhub/*"
  - "apps/publisher"
