openapi: 3.1.0
info:
  title: Mystira Common Types - Events
  version: 1.0.0
  description: Domain event schemas for Mystira platform

components:
  schemas:
    # Base Event Types
    DomainEvent:
      type: object
      required:
        - occurredAt
      properties:
        occurredAt:
          type: string
          format: date-time
          description: When the event occurred (UTC)

    IntegrationEvent:
      allOf:
        - $ref: '#/components/schemas/DomainEvent'
        - type: object
          required:
            - eventId
          properties:
            eventId:
              type: string
              format: uuid
              description: Unique event ID for idempotency

    # Account Events
    AccountCreated:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
            - email
          properties:
            type:
              type: string
              const: AccountCreated
            accountId:
              type: string
              description: The unique account ID
            email:
              type: string
              format: email
              description: The user's email address
            provider:
              type: string
              nullable: true
              description: Authentication provider (e.g., "entra", "google")

    AccountUpdated:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
            - updatedFields
          properties:
            type:
              type: string
              const: AccountUpdated
            accountId:
              type: string
            updatedFields:
              type: array
              items:
                type: string

    AccountDeleted:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
          properties:
            type:
              type: string
              const: AccountDeleted
            accountId:
              type: string
            isSoftDelete:
              type: boolean
              default: true

    # Session Events
    SessionStarted:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - sessionId
            - accountId
            - scenarioId
          properties:
            type:
              type: string
              const: SessionStarted
            sessionId:
              type: string
            accountId:
              type: string
            scenarioId:
              type: string

    SessionCompleted:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - sessionId
            - accountId
            - scenarioId
            - durationSeconds
          properties:
            type:
              type: string
              const: SessionCompleted
            sessionId:
              type: string
            accountId:
              type: string
            scenarioId:
              type: string
            durationSeconds:
              type: integer
            outcome:
              type: string
              nullable: true

    SessionAbandoned:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - sessionId
            - accountId
            - durationSeconds
          properties:
            type:
              type: string
              const: SessionAbandoned
            sessionId:
              type: string
            accountId:
              type: string
            durationSeconds:
              type: integer
            lastProgressPoint:
              type: string
              nullable: true

    # Content Events
    ScenarioCreated:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - scenarioId
            - title
            - authorId
          properties:
            type:
              type: string
              const: ScenarioCreated
            scenarioId:
              type: string
            title:
              type: string
            authorId:
              type: string
            isPublished:
              type: boolean
              default: false

    ScenarioUpdated:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - scenarioId
            - updatedFields
          properties:
            type:
              type: string
              const: ScenarioUpdated
            scenarioId:
              type: string
            updatedFields:
              type: array
              items:
                type: string
            version:
              type: integer
              nullable: true

    ScenarioPublished:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - scenarioId
            - title
            - authorId
          properties:
            type:
              type: string
              const: ScenarioPublished
            scenarioId:
              type: string
            title:
              type: string
            authorId:
              type: string

    ScenarioUnpublished:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - scenarioId
          properties:
            type:
              type: string
              const: ScenarioUnpublished
            scenarioId:
              type: string
            reason:
              type: string
              nullable: true

    MediaUploaded:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - mediaId
            - uploaderId
            - mimeType
            - sizeBytes
          properties:
            type:
              type: string
              const: MediaUploaded
            mediaId:
              type: string
            uploaderId:
              type: string
            mimeType:
              type: string
            sizeBytes:
              type: integer
              format: int64

    # Cache Events
    CacheInvalidated:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - keyPattern
            - entityType
            - sourceService
          properties:
            type:
              type: string
              const: CacheInvalidated
            keyPattern:
              type: string
              description: Cache key pattern to invalidate (supports wildcards)
            entityType:
              type: string
            entityId:
              type: string
              nullable: true
            sourceService:
              type: string

    CacheWarmupRequested:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - entityType
          properties:
            type:
              type: string
              const: CacheWarmupRequested
            entityType:
              type: string
              description: The entity type to warm
            entityIds:
              type: array
              items:
                type: string
              nullable: true
              description: Specific entity IDs to warm (null = all)
            priority:
              type: integer
              default: 0
              description: Priority level (higher = more urgent)

    # AI Events
    StoryGenerationRequested:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - requestId
            - scenarioId
            - accountId
          properties:
            type:
              type: string
              const: StoryGenerationRequested
            requestId:
              type: string
              description: The request ID for tracking
            scenarioId:
              type: string
              description: The scenario being generated for
            accountId:
              type: string
              description: The requesting user's account ID
            prompt:
              type: string
              nullable: true
              description: The prompt or context for generation

    StoryGenerationCompleted:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - requestId
            - scenarioId
            - durationMs
          properties:
            type:
              type: string
              const: StoryGenerationCompleted
            requestId:
              type: string
            scenarioId:
              type: string
            durationMs:
              type: integer
              description: Time taken in milliseconds
            tokensUsed:
              type: integer
              nullable: true
              description: Token count used
            model:
              type: string
              nullable: true
              description: Model used for generation

    StoryGenerationFailed:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - requestId
            - scenarioId
            - errorCode
            - errorMessage
          properties:
            type:
              type: string
              const: StoryGenerationFailed
            requestId:
              type: string
            scenarioId:
              type: string
            errorCode:
              type: string
            errorMessage:
              type: string
            isRetryable:
              type: boolean
              default: false

    # User Events
    UserLoggedIn:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
            - provider
          properties:
            type:
              type: string
              const: UserLoggedIn
            accountId:
              type: string
            provider:
              type: string
              description: Authentication provider used
            clientIp:
              type: string
              nullable: true
              description: Client IP address (masked for privacy)
            userAgent:
              type: string
              nullable: true

    UserLoggedOut:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
          properties:
            type:
              type: string
              const: UserLoggedOut
            accountId:
              type: string
            isExplicit:
              type: boolean
              default: true
              description: Whether this was an explicit logout or session expiry

    PasswordResetRequested:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
            - email
            - expiresAt
          properties:
            type:
              type: string
              const: PasswordResetRequested
            accountId:
              type: string
            email:
              type: string
              format: email
            expiresAt:
              type: string
              format: date-time
              description: Expiry time for the reset token

    PasswordChanged:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - accountId
          properties:
            type:
              type: string
              const: PasswordChanged
            accountId:
              type: string
            viaReset:
              type: boolean
              default: false
              description: Whether this was via reset flow or user-initiated

    # Notification Events
    NotificationSent:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - notificationId
            - recipientId
            - notificationType
            - template
          properties:
            type:
              type: string
              const: NotificationSent
            notificationId:
              type: string
            recipientId:
              type: string
              description: The recipient's account ID
            notificationType:
              type: string
              description: Notification type (email, push, in-app)
            template:
              type: string
              description: Template or category

    EmailSent:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - emailId
            - recipientEmail
            - template
            - subject
          properties:
            type:
              type: string
              const: EmailSent
            emailId:
              type: string
              description: The email ID for tracking
            recipientEmail:
              type: string
              description: The recipient's email (masked)
            template:
              type: string
              description: Email template used
            subject:
              type: string
              description: Subject line

    NotificationFailed:
      allOf:
        - $ref: '#/components/schemas/IntegrationEvent'
        - type: object
          required:
            - type
            - notificationId
            - recipientId
            - reason
          properties:
            type:
              type: string
              const: NotificationFailed
            notificationId:
              type: string
            recipientId:
              type: string
            reason:
              type: string
              description: Error reason
            isRetryable:
              type: boolean
              default: false

    # Union type for all events
    MystiraEvent:
      oneOf:
        # Account Events
        - $ref: '#/components/schemas/AccountCreated'
        - $ref: '#/components/schemas/AccountUpdated'
        - $ref: '#/components/schemas/AccountDeleted'
        # Session Events
        - $ref: '#/components/schemas/SessionStarted'
        - $ref: '#/components/schemas/SessionCompleted'
        - $ref: '#/components/schemas/SessionAbandoned'
        # Content Events
        - $ref: '#/components/schemas/ScenarioCreated'
        - $ref: '#/components/schemas/ScenarioUpdated'
        - $ref: '#/components/schemas/ScenarioPublished'
        - $ref: '#/components/schemas/ScenarioUnpublished'
        - $ref: '#/components/schemas/MediaUploaded'
        # Cache Events
        - $ref: '#/components/schemas/CacheInvalidated'
        - $ref: '#/components/schemas/CacheWarmupRequested'
        # AI Events
        - $ref: '#/components/schemas/StoryGenerationRequested'
        - $ref: '#/components/schemas/StoryGenerationCompleted'
        - $ref: '#/components/schemas/StoryGenerationFailed'
        # User Events
        - $ref: '#/components/schemas/UserLoggedIn'
        - $ref: '#/components/schemas/UserLoggedOut'
        - $ref: '#/components/schemas/PasswordResetRequested'
        - $ref: '#/components/schemas/PasswordChanged'
        # Notification Events
        - $ref: '#/components/schemas/NotificationSent'
        - $ref: '#/components/schemas/EmailSent'
        - $ref: '#/components/schemas/NotificationFailed'
      discriminator:
        propertyName: type
        mapping:
          # Account Events
          AccountCreated: '#/components/schemas/AccountCreated'
          AccountUpdated: '#/components/schemas/AccountUpdated'
          AccountDeleted: '#/components/schemas/AccountDeleted'
          # Session Events
          SessionStarted: '#/components/schemas/SessionStarted'
          SessionCompleted: '#/components/schemas/SessionCompleted'
          SessionAbandoned: '#/components/schemas/SessionAbandoned'
          # Content Events
          ScenarioCreated: '#/components/schemas/ScenarioCreated'
          ScenarioUpdated: '#/components/schemas/ScenarioUpdated'
          ScenarioPublished: '#/components/schemas/ScenarioPublished'
          ScenarioUnpublished: '#/components/schemas/ScenarioUnpublished'
          MediaUploaded: '#/components/schemas/MediaUploaded'
          # Cache Events
          CacheInvalidated: '#/components/schemas/CacheInvalidated'
          CacheWarmupRequested: '#/components/schemas/CacheWarmupRequested'
          # AI Events
          StoryGenerationRequested: '#/components/schemas/StoryGenerationRequested'
          StoryGenerationCompleted: '#/components/schemas/StoryGenerationCompleted'
          StoryGenerationFailed: '#/components/schemas/StoryGenerationFailed'
          # User Events
          UserLoggedIn: '#/components/schemas/UserLoggedIn'
          UserLoggedOut: '#/components/schemas/UserLoggedOut'
          PasswordResetRequested: '#/components/schemas/PasswordResetRequested'
          PasswordChanged: '#/components/schemas/PasswordChanged'
          # Notification Events
          NotificationSent: '#/components/schemas/NotificationSent'
          EmailSent: '#/components/schemas/EmailSent'
          NotificationFailed: '#/components/schemas/NotificationFailed'
