using Mystira.Domain.Results;
using Mystira.Domain.Entities;
using Mystira.Domain.Models;
using Mystira.Domain.Enums;

namespace Mystira.Integration.Tests;

/// <summary>
/// Integration tests that verify cross-package functionality works correctly.
/// These tests ensure that the Mystira packages integrate properly together.
/// </summary>
[Trait("Category", "Integration")]
public class PackageIntegrationTests
{
    [Fact]
    public void DomainEntity_CanBeCreated_WithAutoGeneratedId()
    {
        // Arrange & Act
        var account = new Account
        {
            Email = "test@example.com",
            DisplayName = "Test User"
        };

        // Assert
        account.Id.Should().NotBeNullOrEmpty();
        account.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }

    [Fact]
    public void CoreResult_CanWrapDomainEntity()
    {
        // Arrange
        var account = new Account
        {
            Email = "test@example.com",
            DisplayName = "Test User",
            Status = AccountStatus.Active
        };

        // Act
        var result = Result<Account>.Success(account);

        // Assert
        result.IsSuccess.Should().BeTrue();
        result.Value.Should().Be(account);
        result.Value.Email.Should().Be("test@example.com");
    }

    [Fact]
    public void CoreResult_FailureWithError_PreservesDomainContext()
    {
        // Arrange
        var error = Error.NotFound("Account", "test-id-123");

        // Act
        var result = Result<Account>.Failure(error);

        // Assert
        result.IsFailure.Should().BeTrue();
        result.Error.Code.Should().Be("NOT_FOUND");
        result.Error.Message.Should().Contain("Account");
    }

    [Fact]
    public void DomainAccount_LoginBehavior_WorksCorrectly()
    {
        // Arrange
        var account = new Account
        {
            Email = "test@example.com",
            Status = AccountStatus.Active
        };

        // Act & Assert - Successful login
        account.RecordSuccessfulLogin();
        account.LastLoginAt.Should().NotBeNull();
        account.FailedLoginAttempts.Should().Be(0);
        account.CanLogin.Should().BeTrue();

        // Act & Assert - Failed logins leading to lockout
        for (int i = 0; i < 5; i++)
        {
            account.RecordFailedLogin(maxAttempts: 5);
        }
        account.CanLogin.Should().BeFalse();
        account.IsLockedOut.Should().BeTrue();
    }

    [Fact]
    public void DomainEntityId_GeneratesUniqueIds()
    {
        // Arrange & Act
        var ids = Enumerable.Range(0, 100)
            .Select(_ => EntityId.NewId())
            .ToList();

        // Assert - All IDs should be unique
        ids.Should().OnlyHaveUniqueItems();
    }

    [Fact]
    public void CoreResultExtensions_MapOperation_IntegratesWithDomain()
    {
        // Arrange
        var account = new Account
        {
            Email = "test@example.com",
            DisplayName = "Test User"
        };
        var result = Result<Account>.Success(account);

        // Act
        var emailResult = result.Match(
            onSuccess: a => a.Email,
            onFailure: _ => string.Empty);

        // Assert
        emailResult.Should().Be("test@example.com");
    }
}
