name: "[Build & Deploy] Dev"

on:
  push:
    branches: [dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy after build'
        required: false
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always
  ACR_NAME: myssharedacr
  IMAGE_NAME: devhub

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      image_digest: ${{ steps.push.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.MYSTIRA_AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,format=short
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            LEPTOS_ENV=production

      - name: Generate summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Image | \`${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Tag | \`${{ steps.meta.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Digest | \`${{ steps.push.outputs.digest }}\` |" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Trigger Dev Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev' && (github.event_name == 'push' || inputs.deploy)
    steps:
      - name: Trigger workspace deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MYSTIRA_WORKSPACE_DISPATCH_TOKEN }}
          repository: phoenixvc/Mystira.workspace
          event-type: devhub-deploy
          client-payload: |
            {
              "environment": "dev",
              "image_tag": "${{ needs.build.outputs.image_tag }}",
              "ref": "${{ github.sha }}",
              "triggered_by": "${{ github.actor }}",
              "repository": "${{ github.repository }}"
            }

      - name: Generate summary
        run: |
          echo "## Deployment Triggered" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Triggered deployment to dev environment via Mystira.workspace" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | dev |" >> $GITHUB_STEP_SUMMARY
          echo "| Image Tag | \`${{ needs.build.outputs.image_tag }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
