name: CI

on:
  push:
    branches: [dev, main]
    paths:
      - "Mystira.DevHub/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Mystira.DevHub
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: Mystira.DevHub/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc --noEmit
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}

      - name: Lint
        run: pnpm lint
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}

  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Mystira.DevHub/src-tauri
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: Mystira.DevHub/src-tauri

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Mystira.DevHub
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: Mystira.DevHub/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test -- --run
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}

  test-rust:
    name: Test Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Mystira.DevHub/src-tauri
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: Mystira.DevHub/src-tauri

      - name: Run tests
        run: cargo test --all-features
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}

  build:
    name: Build (${{ matrix.platform.os }})
    needs: [lint-frontend, lint-rust, test-frontend, test-rust]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: devhub-linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: devhub-windows-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: devhub-macos-x64
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        working-directory: Mystira.DevHub
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: Mystira.DevHub/pnpm-lock.yaml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies (Linux)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: Mystira.DevHub/src-tauri

      - run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Build Tauri app
        run: pnpm tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact }}
          path: |
            Mystira.DevHub/src-tauri/target/release/bundle/**/*
          retention-days: 7
          if-no-files-found: warn
