name: "[Release] Desktop App"

# Creates a GitHub release with desktop binaries for all platforms
# Triggered by version tags (v*) or manual dispatch

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: devhub-linux-x64
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: devhub-windows-x64
          - name: macOS (Intel)
            os: macos-latest
            target: x86_64-apple-darwin
            artifact: devhub-macos-x64
          - name: macOS (Apple Silicon)
            os: macos-latest
            target: aarch64-apple-darwin
            artifact: devhub-macos-arm64
    runs-on: ${{ matrix.platform.os }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    defaults:
      run:
        working-directory: Mystira.DevHub
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: Mystira.DevHub/pnpm-lock.yaml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install system dependencies (Linux)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: Mystira.DevHub/src-tauri
          shared-key: tauri-release-${{ matrix.platform.target }}

      - run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Build Tauri app
        run: pnpm tauri build --target ${{ matrix.platform.target }}
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact }}
          path: |
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.AppImage
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.deb
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.msi
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.exe
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.dmg
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.app.tar.gz
            Mystira.DevHub/src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*.sig
          retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: |
          echo "Downloaded artifacts:"
          find artifacts -type f -name "*" | head -50

      - name: Prepare release files
        id: prepare
        run: |
          mkdir -p release-files

          # Copy and rename artifacts for release
          find artifacts -type f \( -name "*.AppImage" -o -name "*.deb" -o -name "*.msi" -o -name "*.exe" -o -name "*.dmg" -o -name "*.app.tar.gz" -o -name "*.sig" \) -exec cp {} release-files/ \;

          echo "Release files:"
          ls -la release-files/

      - name: Generate changelog
        id: changelog
        run: |
          # Generate basic changelog from commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            echo "Changes since $LAST_TAG:" > CHANGELOG.md
            git log --pretty=format:"- %s (%h)" $LAST_TAG..HEAD >> CHANGELOG.md
          else
            echo "Initial release" > CHANGELOG.md
          fi
          cat CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.version }}
          name: DevHub ${{ needs.build.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ inputs.prerelease || false }}
          files: release-files/*
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify workspace
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MYSTIRA_WORKSPACE_DISPATCH_TOKEN }}
          repository: phoenixvc/Mystira.workspace
          event-type: devhub-release
          client-payload: |
            {
              "version": "${{ needs.build.outputs.version }}",
              "ref": "${{ github.sha }}",
              "triggered_by": "${{ github.actor }}",
              "repository": "${{ github.repository }}",
              "release_url": "https://github.com/${{ github.repository }}/releases/tag/${{ needs.build.outputs.version }}"
            }

      - name: Generate summary
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Version | \`${{ needs.build.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Pre-release | ${{ inputs.prerelease || 'false' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Platforms" >> $GITHUB_STEP_SUMMARY
          echo "- Linux (x64): AppImage, .deb" >> $GITHUB_STEP_SUMMARY
          echo "- Windows (x64): .msi, .exe" >> $GITHUB_STEP_SUMMARY
          echo "- macOS (Intel): .dmg, .app.tar.gz" >> $GITHUB_STEP_SUMMARY
          echo "- macOS (Apple Silicon): .dmg, .app.tar.gz" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View Release](https://github.com/${{ github.repository }}/releases/tag/${{ needs.build.outputs.version }})" >> $GITHUB_STEP_SUMMARY
