apiVersion: v1
kind: ConfigMap
metadata:
  name: mys-admin-api-config
  labels:
    app: mys-admin-api
    component: api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
